FROM golang:alpine AS build

WORKDIR /app

# ./ is same as /app/ ... as we have set the workdir as /app
COPY go.mod go.sum ./ 
RUN go mod download

COPY relay/. .
COPY common ./common

RUN go build -o relay ./main.go


FROM alpine:latest

WORKDIR /app

COPY --from=build /app/relay .
COPY relay/config.yaml .

ENTRYPOINT ["./relay"]